export const RegisterResult = {
  SUCCESS: 'SUCCESS',
  EMPTY_FIELD: 'EMPTY_FIELD',
  USERNAME_EXISTS: 'USERNAME_EXISTS',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  PASSWORD_INVALID: 'PASSWORD_INVALID',
  EMAIL_INVALID: 'EMAIL_INVALID'
}
